server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db?useSSL=false
    username: bestuser
    password: bestuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  token:
    secret: secret
    expired: 3600000
